server:
  port: 8080

spring:
  profiles:
    default: local
  jackson:
    default-property-inclusion: non_null

app:
  cache:
    sync-window-minutes: 5

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/forbidden_words?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
