server:
  port: ${FORBIDDEN_WORDS_SERVER_PORT:8084}

spring:
  profiles:
    default: mysql
  sql:
    init:
      mode: never
  flyway:
    enabled: true
  jackson:
    default-property-inclusion: non_null

app:
  cache:
    sync-window-minutes: 5

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${XM4_MYSQL_URL:jdbc:mysql://127.0.0.1:3307/xm4?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${XM4_MYSQL_USERNAME:root}
    password: ${XM4_MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
