CREATE TABLE forbidden_word (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_forbidden_word_platform UNIQUE (word, platform)
);

CREATE TABLE operation_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(32) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    operator_ip VARCHAR(64) NOT NULL,
    target_word VARCHAR(255) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    operation_time TIMESTAMP NOT NULL
);

CREATE TABLE hit_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(64) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    content CLOB NOT NULL,
    hit_word VARCHAR(255) NOT NULL,
    action VARCHAR(32) NOT NULL,
    action_time TIMESTAMP NOT NULL
);

CREATE TABLE agent_account_operation_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE password_reset_session (
    reset_token VARCHAR(64) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    account VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE password_reset_sms_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reset_token VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL,
    account VARCHAR(64) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    code_hash VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    next_allowed_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
