#!/usr/bin/env bash
set -euo pipefail

REMOTE_HOST="${TENCENT_CLOUD_HOST:-42.193.201.236}"
REMOTE_PORT="${TENCENT_CLOUD_SSH_PORT:-22}"
REMOTE_USER="${TENCENT_CLOUD_SSH_USER:-ubuntu}"
LOCAL_PORT="${MYSQL_TUNNEL_LOCAL_PORT:-3307}"
REMOTE_MYSQL_HOST="${MYSQL_REMOTE_HOST:-127.0.0.1}"
REMOTE_MYSQL_PORT="${MYSQL_REMOTE_PORT:-3306}"

echo "Opening SSH tunnel: 127.0.0.1:${LOCAL_PORT} -> ${REMOTE_MYSQL_HOST}:${REMOTE_MYSQL_PORT} on ${REMOTE_USER}@${REMOTE_HOST}"
echo "Keep this terminal open while running local services."

ssh -N \
  -L "${LOCAL_PORT}:${REMOTE_MYSQL_HOST}:${REMOTE_MYSQL_PORT}" \
  -p "${REMOTE_PORT}" \
  "${REMOTE_USER}@${REMOTE_HOST}"